src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductsRepository::class)]
class Products
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $Categories = null;

    /**
     * @var Collection<int, Images>
     */
    #[ORM\OneToMany(targetEntity: Images::class, mappedBy: 'Products', orphanRemoval: true)]
    private Collection $images;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->images = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCategories(): ?Categories
    {
        return $this->Categories;
    }

    public function setCategories(?Categories $Categories): static
    {
        $this->Categories = $Categories;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setProducts($this);
        }

        return $this;
    }

    public function removeImage(Images $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProducts() === $this) {
                $image->setProducts(null);
            }
        }

        return $this;
    }


    

    
}

src/Controller/Admin/ProductsController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Products;
use App\Form\ProductsFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/products', name: 'admin_products_')]
class ProductsController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(): Response
    {
        return $this->render('admin/products/index.html.twig');
    }

    #[Route('/ajout', name: 'add')]
    public function add(Request $request,EntityManagerInterface $em): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        // Créer un nouveau produit
        $product = new Products();

        //  On crée le formulaire
        $productForm = $this->createForm(ProductsFormType::class, $product);

        //Traitement de la requete du formulaire
        $productForm->handleRequest($request);

        // Vérification du formulaire (soumis et valide)
        if($productForm->isSubmitted() && $productForm->isValid()){

            //On arrondit le prix
            $prix= $product->getPrice() * 100;
            $product->setPrice($prix);


            //Stockage
            $em->persist($product);
            $em->flush();

            //Redirection
            return $this->redirectToRoute('admin_products_index');

        }


        // return $this->render('admin/products/add.html.twig',[
        //     'productForm'=>$productForm->createView()
        // ]);

        return $this->renderForm('admin/products/add.html.twig',compact('productForm'));
    }






    #[Route('/edition/{id}', name: 'edit')]
    public function edit(Products $product,Request $request,EntityManagerInterface $em): Response
    {

        // On utilise le Voter
        $this->denyAccessUnlessGranted('PRODUCT_EDIT', $product);

        //On divise le prix par 100
        $prix= $product->getPrice() / 100;
        $product->setPrice($prix);

        //  On crée le formulaire
        $productForm = $this->createForm(ProductsFormType::class, $product);

        //Traitement de la requete du formulaire
        $productForm->handleRequest($request);

        // Vérification du formulaire (soumis et valide)
        if($productForm->isSubmitted() && $productForm->isValid()){

            //On arrondit le prix
            $prix= $product->getPrice() * 100;
            $product->setPrice($prix);

            //Stockage
            $em->persist($product);
            $em->flush();

            //Redirection
            return $this->redirectToRoute('admin_products_index');

        }
        return $this->renderForm('admin/products/edit.html.twig',compact('productForm'));
    }

    #[Route('/suppression/{id}', name: 'delete')]
    public function delete(Products $product): Response
    {
        $this->denyAccessUnlessGranted('PRODUCT_DELETE', $product);
        return $this->render('admin/products/index.html.twig');
    }
}

src/Controller/ProductsController.php
<?php

namespace App\Controller;
use App\Entity\Products;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


#[Route('/produits',name:'products_')]
class ProductsController extends AbstractController
{

    #[Route('/', name: 'index')]
    public function index() : Response {

        return $this->render('products/index.html.twig');
    }

#[Route('/{name}', name:'details')]
public function details(Products $product) :Response {

    return $this->render('products/details.html.twig',compact('product'));
}
}

templates/products/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de
	{{ product.name }}
{% endblock %}

{% block body %}


	<main class="container">
		<section class="row">
			<div class="col-12">
				<h1>{{ product.name }}</h1>
			</div>
			<div class="col-6">
				<div id="carouselExampleIndicators" class="carousel slide">
					<div class="carousel-indicators">
						{% for iteration in 1..product.images|length %}
							<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ iteration - 1 }}" {{ (loop.first) ? 'class="active" aria-current="true"' : '' }} aria-label="Slide  {{ iteration }}"></button>
						{% endfor %}
					</div>
					<div class="carousel-inner">
						{% for image in product.images %}
							<div class="carousel-item {{ (loop.first) ? 'active' : '' }}">
								<img src="{{ asset('assets/uploads/') ~ image.name }}" class="d-block img-thumbnail img-fluid w-100" alt="...">
							</div>
						{% endfor %}
					</div>
					<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Previous</span>
					</button>
					<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Next</span>
					</button>
				</div>
			</div>
			<div class="col-6">
				<p>Catégorie :
					{{ product.categories.name }}
				</p>
				<p>Prix :
					{{ product.price /100 }}€</p>
				{% if product.stock > 0 %}

				<a href="#" class="btn btn-success">Ajouter au pannier</a>
				{% else %}
				<p class="text-danger">En rupture de stock</p>
				{% endif %}
				
			</div>
		</section>
	</main>

{% endblock %}

templates/products/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des produits{% endblock %}

{% block body %}
<p>Liste des produits</p>
{% endblock %}